src/main/java/mom/trd/opentheso/SelectedBeans/DownloadBean.java
package mom.trd.opentheso.SelectedBeans;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.io.Serializable;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import mom.trd.opentheso.bdd.helper.ConceptHelper;
import mom.trd.opentheso.bdd.helper.nodes.NodeLang;
import mom.trd.opentheso.bdd.helper.nodes.NodePreference;
import mom.trd.opentheso.bdd.helper.PreferencesHelper;
import mom.trd.opentheso.bdd.helper.nodes.group.NodeGroup;
import mom.trd.opentheso.core.exports.helper.ExportTabulateHelper;
import mom.trd.opentheso.core.exports.helper.ExportThesaurus;
import mom.trd.opentheso.core.exports.helper.ExportTxtHelper;
import mom.trd.opentheso.core.exports.old.ExportFromBDD;
import mom.trd.opentheso.core.exports.old.ExportFromBDD_Frantiq;
import mom.trd.opentheso.core.exports.pdf.WritePdf;
import mom.trd.opentheso.core.exports.rdf4j.WriteRdf4j;
import mom.trd.opentheso.core.exports.rdf4j.helper.ExportRdf4jHelper;
import mom.trd.opentheso.core.jsonld.helper.JsonHelper;
import org.eclipse.rdf4j.rio.RDFFormat;
import org.eclipse.rdf4j.rio.Rio;
import org.primefaces.model.ByteArrayContent;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import skos.SKOSXmlDocument;

@ManagedBean(name = "downloadBean", eager = true)
@SessionScoped

public class DownloadBean implements Serializable {

    private String skos;
    private StreamedContent file;

    @ManagedProperty(value = "#{vue}")
    private Vue vue;

    @ManagedProperty(value = "#{poolConnexion}")
    private Connexion connect;

    @ManagedProperty(value = "#{langueBean}")
    private LanguageBean languageBean;

    @ManagedProperty(value = "#{currentUser}") 
    private CurrentUser2 currentUser;
    
    @ManagedProperty(value = "#{roleOnTheso}")
    private RoleOnThesoBean roleOnTheso;  

    private String nomUsu;

    private int progress_per_100 = 0;

    public int getProgress_per_100() {
        return progress_per_100;
    }

    public void setProgress_per_100(int progress_per_100) {
        this.progress_per_100 = progress_per_100;
    }

    public int getProgress_abs() {
        return progress_abs;
    }

    public void setProgress_abs(int progress_abs) {
        this.progress_abs = progress_abs;
    }

    public double getSizeOfTheso() {
        return sizeOfTheso;
    }

    private int progress_abs = 0;
    private double sizeOfTheso;

    public int getProgress() {
        return progress_per_100;
    }

    @PostConstruct
    public void initTerme() {
        if (currentUser.getUser() == null || roleOnTheso.getNodePreference() == null) {
            return;
        }
    }

    /**
     * Récupération des préférences
     *
     * @return la ressourceBundle des préférences
     */
    private ResourceBundle getBundlePref() {
        FacesContext context = FacesContext.getCurrentInstance();
        ResourceBundle bundlePref = context.getApplication().getResourceBundle(context, "pref");
        return bundlePref;
    }

    public String conceptSkos(String idC, String idTheso) {
        ExportFromBDD exportFromBDD = new ExportFromBDD();

        exportFromBDD.setServerAdress(roleOnTheso.getNodePreference().getCheminSite());
        exportFromBDD.setServerArk(roleOnTheso.getNodePreference().getServeurArk());
        exportFromBDD.setArkActive(roleOnTheso.getNodePreference().isUseArk());

        return exportFromBDD.exportConcept(connect.getPoolConnexion(),
                idTheso,
                idC).toString();

        //   new ExportFromBDD().exportConcept(connect.getPoolConnexion(), idTheso, idC).toString();
    }

    public String groupSkos(String idGroup, String idTheso) {
        ExportFromBDD exportFromBDD = new ExportFromBDD();
        exportFromBDD.setServerAdress(roleOnTheso.getNodePreference().getCheminSite());
        exportFromBDD.setServerArk(roleOnTheso.getNodePreference().getServeurArk());
        exportFromBDD.setArkActive(roleOnTheso.getNodePreference().isUseArk());

        return exportFromBDD.exportThisGroup(connect.getPoolConnexion(), idTheso, idGroup).toString();
    }

    public String groupJsonLd(String idGroup, String idTheso) {
        ExportFromBDD exportFromBDD = new ExportFromBDD();
        exportFromBDD.setServerAdress(roleOnTheso.getNodePreference().getCheminSite());
        exportFromBDD.setServerArk(roleOnTheso.getNodePreference().getServeurArk());
        exportFromBDD.setArkActive(roleOnTheso.getNodePreference().isUseArk());

        StringBuffer skos_local = exportFromBDD.exportThisGroup(connect.getPoolConnexion(), idTheso, idGroup);

        JsonHelper jsonHelper = new JsonHelper();
        SKOSXmlDocument sKOSXmlDocument = jsonHelper.readSkosDocument(skos_local);
        StringBuffer jsonLd = jsonHelper.getJsonLd(sKOSXmlDocument);
        return jsonLd.toString();
    }

    /*    public void branchSkos(String idC, String idTheso) {
        ExportFromBDD exportFromBDD = new ExportFromBDD();
        exportFromBDD.setServerAdress(serverAdress);
        exportFromBDD.setServerArk(serverArk);
        exportFromBDD.setArkActive(arkActive);

        StringBuffer temp = exportFromBDD.exportBranchOfConcept(connect.getPoolConnexion(), idTheso, idC);
        if (temp.length() <= 1500000) {
            //    if(temp.length() <= 150) {
            skos = temp.toString();
            vue.setBranchToSkos(true);
        } else {
            InputStream stream;
            try {
                stream = new ByteArrayInputStream(temp.toString().getBytes("UTF-8"));
                file = new DefaultStreamedContent(stream, "application/xml ", "downloadedSkos.xml");
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(DownloadBean.class.getName()).log(Level.SEVERE, null, ex);
            }
            vue.setBranchToSkosFile(true);
        }
    }*/
    public void branchGroupSkos(String idGroup, String idTheso) {
        ExportFromBDD exportFromBDD = new ExportFromBDD();
        exportFromBDD.setServerAdress(roleOnTheso.getNodePreference().getCheminSite());
        exportFromBDD.setServerArk(roleOnTheso.getNodePreference().getServeurArk());
        exportFromBDD.setArkActive(roleOnTheso.getNodePreference().isUseArk());

        StringBuffer temp = exportFromBDD.exportGroup(connect.getPoolConnexion(), idTheso, idGroup);
        if (temp.length() <= 1500000) {
            skos = temp.toString();
            vue.setBranchToSkos(true);
        } else {
            InputStream stream;
            try {
                stream = new ByteArrayInputStream(temp.toString().getBytes("UTF-8"));
                file = new DefaultStreamedContent(stream, "application/xml ", "downloadedSkos.xml");
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(DownloadBean.class.getName()).log(Level.SEVERE, null, ex);
            }
            vue.setBranchToSkosFile(true);
        }
    }

    /**
     * Cette fonction permet d'exporter un thésaurus au format SKOS à partir de
     * son identifiant. Le résultat est enregistré dans la variable 'skos' du
     * downloadBean si la taille est petite, ou dans la variable 'file' du
     * downloadBean sinon. Dans le premier cas on affiche la variable, dans le
     * second cas l'utilisateur télécharge de fichier.
     *
     * @param idTheso
     * @return
     */
    public StreamedContent thesoSkos(String idTheso) {

        /**
         * Cette initialisation est pour exporter les PACTOLS au format accepté
         * par Koha
         */
        //ExportFromBDD_Frantiq exportFromBDD = new ExportFromBDD_Frantiq();
        /**
         * ici c'est la classe à utiliser pour un export standard au foramt SKOS
         */
        ExportFromBDD exportFromBDD = new ExportFromBDD();

        exportFromBDD.setServerAdress(roleOnTheso.getNodePreference().getCheminSite());
        exportFromBDD.setServerArk(roleOnTheso.getNodePreference().getServeurArk());
        exportFromBDD.setArkActive(roleOnTheso.getNodePreference().isUseArk());

        StringBuffer skos_local = exportFromBDD.exportThesaurus(connect.getPoolConnexion(), idTheso);
        InputStream stream;

        try {
            stream = new ByteArrayInputStream(skos_local.toString().getBytes("UTF-8"));
            file = new DefaultStreamedContent(stream, "application/xml", idTheso + "_skos.xml");
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(DownloadBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        vue.setThesoToSkosCsvFile(true);
        return file;


        /*        if (temp.length() <= 1500000) {
            skos = temp.toString();
            vue.setThesoToSkosCsv(true);
        } else {
            InputStream stream;
            try {
                stream = new ByteArrayInputStream(temp.toString().getBytes("UTF-8"));
                file = new DefaultStreamedContent(stream, "application/xml ", "downloadedSkos.xml");
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(DownloadBean.class.getName()).log(Level.SEVERE, null, ex);
            }
            vue.setThesoToSkosCsvFile(true);
        }*/
    }

    private WriteRdf4j loadExportHelper(String idTheso, List<NodeLang> selectedLanguages, List<NodeGroup> selectedGroups) {

src/main/webapp/dialogs/import/importBranchDlg.xhtml
<!DOCTYPE html [
    <!ENTITY nbsp "&#160;"> 
    ]>
    <ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:p="http://primefaces.org/ui">

        <p:dialog id="idImportBranchDlg"  header="#{langueBean.getMsg('edit.import')}" styleClass="styleText2" widgetVar="importBranchDlg" modal="true" resizable="false"  >

                




            <h:form style="text-align: left; padding: 10px; max-width: 550px; overflow: auto;">

                    <p:messages showDetail="true">
                        <p:autoUpdate />
                    </p:messages>  
                <h:outputText value="#{langueBean.getMsg('edit.formDate')}" /> <p:graphicImage id="question" value="images/iconeQuestion.png" /> :
                <p:tooltip id="toolTipFade" for="question" value="#{langueBean.getMsg('edit.dateExemple')}" />
                <h:inputText value="#{rdf4jFileBean.formatDate}" />
                <br/><br/>
                <p:outputLabel for="idTypeImportSingle" value="#{langueBean.getMsg('export.type')} :" />
                <p:selectOneMenu id="idTypeImportSingle" value="#{rdf4jFileBean.typeImport}">
                    <f:selectItem itemLabel="Skos" itemValue="0" />
                    <f:selectItem itemLabel="Json-ld" itemValue="1" />
                    <f:selectItem itemLabel="Turtle" itemValue="2" />
                </p:selectOneMenu>
                <br/><br/>
                <p:fileUpload label="#{langueBean.getMsg('upOpt1')}" uploadLabel="#{langueBean.getMsg('upOpt2')}" allowTypes="/(\.|\/)(skos|rdf|xml)$/"
                              cancelLabel="#{langueBean.getMsg('upOpt3')}" fileUploadListener="#{rdf4jFileBean.chargeFile}" process="@form"
                              onstart="PrimeFaces.monitorDownload(start_import_branche);PF('pbAjax').start();" 
                              update="@form" oncomplete="PrimeFaces.monitorDownload(stop_import_branche)" disabled="#{!rdf4jFileBean.uploadEnable}"/>
                
                
                
                <br/> 
                <p:commandButton value="#{langueBean.getMsg('btnAdd')}" disabled="#{!rdf4jFileBean.BDDinsertEnable}"
                                 actionListener="#{rdf4jFileBean.inserBranch(editionBean.selectedUserGroup,selectedTerme)}" 
                                 onclick="PrimeFaces.monitorDownload(start_import_branche);PF('pbAjax').start();" 
                                 oncomplete="PrimeFaces.monitorDownload(stop_import_branche);PF('importBranchDlg').hide();" 
                                 update=":idImportBranchDlg,:accordeonTree,:panContenu"
                                 />
            </h:form>



            <p:dialog modal="true" widgetVar="importBrancheWait" header="#{langueBean.getMsg('export.wait')}" draggable="false" closable="false" resizable="false">
                <p:graphicImage id="exportLoadingImage2" value="/images/loading.gif" width="50"/>

                <br />
                <p:progressBar widgetVar="pbAjax" ajax="true" value="0" labelTemplate="{value}%" styleClass="animated" global="false"/>


            </p:dialog>


        </p:dialog>

        <script type="text/javascript">
            function start_import_branche() {
                PF('importBrancheWait').show();
            }

            function stop_import_branche() {
                PF('importBrancheWait').hide();

            }
        </script> 


    </ui:composition>

src/main/webapp/dialogs/import/importCSVDlg.xhtml
<!DOCTYPE html [
    <!ENTITY nbsp "&#160;"> 
    ]>
    <ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:p="http://primefaces.org/ui">

        <p:dialog id="idImportCSVDlg"  header="#{langueBean.getMsg('edit.importcsv')}" styleClass="styleText2" widgetVar="importCSVDlg" modal="true" resizable="false"  >
            <h:panelGroup id="panCsv">
                <h:panelGroup layout="block" >
                    <div class="importerTheso">
                        <h:form style="text-align: left; padding: 10px; max-width: 550px; overflow: auto;">
                            <table>
                                <tr>
                                    <td>
                                        <h:outputText value="#{langueBean.getMsg('theso.id')}" /> <p:graphicImage id="question1" value="images/iconeQuestion.png" /> :
                                        <p:tooltip id="toolTipFade1" for="question1" value="Il faut créer un thésaurus vide avant, puis mettre l'identifiant de ce thésaurus ici !!" />
                                    </td>
                                    <td><h:inputText value="#{fileBean.idTheso}" /></td>
                                </tr>
                                <tr>
                                    <td>
                                        <h:outputText value="#{langueBean.getMsg('edit.sep1')}" /> <p:graphicImage id="question2" value="images/iconeQuestion.png" /> :
                                        <p:tooltip id="toolTipFade2" for="question2" value="" />
                                    </td>
                                    <td><h:inputText value="#{fileBean.sepCol}" /></td>
                                </tr>
                                <tr>
                                    <td>
                                        <h:outputText value="#{langueBean.getMsg('edit.sep2')}" /> <p:graphicImage id="question3" value="images/iconeQuestion.png" /> :
                                        <p:tooltip id="toolTipFade3" for="question3" value="" />
                                    </td>
                                    <td><h:inputText value="#{fileBean.sepChamps}" /></td>
                                </tr>
                                <tr>
                                    <td>
                                        <h:outputText value="#{langueBean.getMsg('edit.sep3')}" /> <p:graphicImage id="question4" value="images/iconeQuestion.png" /> :
                                        <p:tooltip id="toolTipFade4" for="question4" value="" />
                                    </td>
                                    <td><h:inputText value="#{fileBean.sepLangue}" /></td>
                                </tr>
                                <tr>
                                    <td>
                                        <h:outputText value="#{langueBean.getMsg('edit.formDate')}" /> <p:graphicImage id="question5" value="images/iconeQuestion.png" /> :
                                        <p:tooltip id="toolTipFade5" for="question5" value="#{langueBean.getMsg('edit.dateExemple')}" />
                                    </td>
                                    <td><h:inputText value="#{fileBean.formatDate}" /></td>
                                </tr>
                            </table><br/>
                            <p:fileUpload label="#{langueBean.getMsg('upOpt1')}" uploadLabel="#{langueBean.getMsg('upOpt2')}" allowTypes="/(\.|\/)(csv)$/"
                                          cancelLabel="#{langueBean.getMsg('upOpt3')}" fileUploadListener="#{fileBean.chargeCsv}" process="@form"
                                          update="@form,:panCsv,:tableTheso" />
                        </h:form>
                    </div>
                </h:panelGroup>
            </h:panelGroup>
        </p:dialog>
    </ui:composition>

src/main/webapp/dialogs/import/importDlg.xhtml
<!DOCTYPE html [
    <!ENTITY nbsp "&#160;"> 
    ]>
    <ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:p="http://primefaces.org/ui">

        <p:dialog id="idImportDlg"  header="#{langueBean.getMsg('edit.import')}" styleClass="styleText2" widgetVar="importDlg" modal="true" resizable="false"  >
            <h:form style="text-align: left; padding: 10px; max-width: 550px; overflow: auto;">

                <p:panelGrid styleClass="ui-noborder">
                    <p:row>
                        <p:column >
                            <h:outputText value="#{langueBean.getMsg('edit.formDate')}" /> 
                            <p:graphicImage id="question" value="images/iconeQuestion.png" />
                            <p:tooltip id="toolTipFade" for="question" value="#{langueBean.getMsg('edit.dateExemple')}" />
                        </p:column>
                        <p:column >
                            <h:inputText value="#{rdf4jFileBean.formatDate}" style="font-size: smaller"/>
                        </p:column>
                    </p:row>
                    <p:row>
                        <p:column>
                            <p:outputLabel for="idTypeImportSingle" value="#{langueBean.getMsg('export.type')}" />
                        </p:column>
                        <p:column >
                            <p:selectOneMenu id="idTypeImportSingle" value="#{rdf4jFileBean.typeImport}" style="font-size: smaller">
                                <f:selectItem itemLabel="Skos" itemValue="0" />
                                <f:selectItem itemLabel="Json-ld" itemValue="1" />
                                <f:selectItem itemLabel="Turtle" itemValue="2" />
                            </p:selectOneMenu>
                        </p:column>
                    </p:row>
                    <p:row>
                        <p:column>
                            <h:outputText rendered="#{!currentUser.user.isSuperAdmin}" value="User Group :" />
                        </p:column>
                        <p:column>
                            <p:selectOneMenu rendered="#{!currentUser.user.isSuperAdmin}" id="idGroupSelected" 
                                             value="#{editionBean.selectedUserGroup}" style="font-size: smaller">
                                <f:selectItems value="#{editionBean.userRoleGroups.entrySet()}" var="varSelectedGroup" 
                                               itemLabel="#{varSelectedGroup.value}" itemValue="#{varSelectedGroup.key}"/>
                            </p:selectOneMenu>
                        </p:column>
                    </p:row>                    
                </p:panelGrid>
                
                
                <br/>
                
                <p:panelGrid styleClass="ui-noborder">
                    <f:facet name="header" >
                        <h:outputText value="Récupération de l'identifiant pérenne (ARK ou Handle)" />
                    </f:facet>
                    <p:row>
                        <p:selectOneRadio id="customRadio" value="#{rdf4jFileBean.selectedIdentifier}" layout="custom">
                            <f:selectItem itemLabel="Sans" itemValue="sans" />
                            <f:selectItem itemLabel="Ark" itemValue="ark" />
                            <f:selectItem itemLabel="Handle" itemValue="handle" />
                        </p:selectOneRadio>
                    </p:row>

                    <p:row>
                        <p:column>
                            <p:radioButton id="opt1" for="customRadio" itemIndex="0" />
                        </p:column>
                        <p:column>
                        <h:outputLabel for="opt1" value="Sans" />
                        </p:column>
                        <p:column>
                        <p:outputLabel value="" />
                        </p:column>
                    </p:row>
                    <p:row>
                        <p:column>
                        <p:radioButton id="opt2" for="customRadio" itemIndex="1" />
                        </p:column>
                        <p:column>
                        <h:outputLabel for="opt2" value="Ark" />
                        </p:column>
                        <p:column>
                        <p:outputLabel value="" />
                        </p:column>
                    </p:row>
                    <p:row>
                        <p:column>
                        <p:radioButton id="opt3" for="customRadio" itemIndex="2" />
                        </p:column>
                        <p:column>
                        <h:outputLabel for="opt3" value="Handle -> Préfixe :" />
                        </p:column>
                        <p:column>
                        <p:inputText value="#{rdf4jFileBean.prefixHandle}"/>
                        </p:column>
                    </p:row>    
                </p:panelGrid>
                
                <br/>
                
                <p:fileUpload label="#{langueBean.getMsg('upOpt1')}" uploadLabel="#{langueBean.getMsg('upOpt2')}" allowTypes="/(\.|\/)(skos|rdf|xml|json|ttl)$/"
                              cancelLabel="#{langueBean.getMsg('upOpt3')}" fileUploadListener="#{rdf4jFileBean.chargeFile}" process="@form"
                              onstart="PrimeFaces.monitorDownload(start_import);PF('pbAjax').start();" 
                              update="@form" oncomplete="PrimeFaces.monitorDownload(stop_import)" disabled="#{!rdf4jFileBean.uploadEnable}"/>
        
                <h:outputText value="uri : #{rdf4jFileBean.uri}" />
                <br/> 
                <h:outputText value="#{langueBean.getMsg('import.total')} : #{rdf4jFileBean.total}" />
                <br/> 
                <p:commandButton value="#{langueBean.getMsg('btnAdd')}" disabled="#{!rdf4jFileBean.BDDinsertEnable}"
                                 actionListener="#{rdf4jFileBean.insertBDD(editionBean.selectedUserGroup)}" 
                                 onclick="PrimeFaces.monitorDownload(start_import);PF('pbAjax').start();" 
                                 oncomplete="#{roleOnTheso.showListTheso()}; PrimeFaces.monitorDownload(stop_import);PF('importDlg').hide();" 
                                 update=":idImportDlg,:panSkos,:tableTheso"
                                 style="color: green"
                                 />
                <br/>
                <br/>
                <p:accordionPanel activeIndex="-1">
                    <p:tab title="Info" titleStyleClass="infoAcordionPanel" >
                        <p:scrollPanel mode="native" style="width:400px;height:200px">
                            <pre><h:outputText value="#{rdf4jFileBean.info}" styleClass="infoAcordionPanel" /></pre>
                            <hr/>
                            <pre><h:outputText rendered="#{!rdf4jFileBean.warningIsEmpty()}" value="Warning : #{rdf4jFileBean.warning}" styleClass="warningAcordionPanel" /></pre>
                        </p:scrollPanel>
                    </p:tab>
                    <p:tab title="Error" titleStyleClass="errorAcordionPanel">
                        <p:scrollPanel mode="native" style="width:400px;height:200px">
                            <pre><h:outputText value="#{rdf4jFileBean.error}" styleClass="errorAcordionPanel" /></pre>
                        </p:scrollPanel>
                    </p:tab>

                </p:accordionPanel> 

                <p:dialog modal="true" widgetVar="importWait" header="#{langueBean.getMsg('export.wait')}" draggable="false" closable="false" resizable="false">
                    <p:graphicImage id="exportLoadingImage" value="/images/loading.gif" width="50"/>

                    <br />
                    <p:progressBar widgetVar="pbAjax" ajax="true" value="#{rdf4jFileBean.progress}" labelTemplate="{value}%" styleClass="animated" global="false"/>
                </p:dialog>
            </h:form>
        </p:dialog>
        <script type="text/javascript">
            function start_import() {
                PF('importWait').show();
            }

            function stop_import() {
                PF('importWait').hide();

            }
        </script> 
    </ui:composition>

src/main/webapp/dialogs/import/importSingleConceptDlg.xhtml
<!DOCTYPE html [
    <!ENTITY nbsp "&#160;"> 
    ]>
    <ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:p="http://primefaces.org/ui">

        <p:dialog id="idImportSingleConceptDlg"  header="#{langueBean.getMsg('edit.import')}" styleClass="styleText2" widgetVar="importSingleConceptDlg" modal="true" resizable="false"  >

                




            <h:form style="text-align: left; padding: 10px; max-width: 550px; overflow: auto;">

                    <p:messages showDetail="true">
                        <p:autoUpdate />
                    </p:messages>  
                <h:outputText value="#{langueBean.getMsg('edit.formDate')}" /> <p:graphicImage id="question" value="images/iconeQuestion.png" /> :
                <p:tooltip id="toolTipFade" for="question" value="#{langueBean.getMsg('edit.dateExemple')}" />
                <h:inputText value="#{rdf4jFileBean.formatDate}" />
                <br/><br/>
                <p:outputLabel for="idTypeImportSingle" value="#{langueBean.getMsg('export.type')} :" />
                <p:selectOneMenu id="idTypeImportSingle" value="#{rdf4jFileBean.typeImport}">
                    <f:selectItem itemLabel="Skos" itemValue="0" />
                    <f:selectItem itemLabel="Json-ld" itemValue="1" />
                    <f:selectItem itemLabel="Turtle" itemValue="2" />
                </p:selectOneMenu>
                <br/><br/>
                <p:fileUpload label="#{langueBean.getMsg('upOpt1')}" uploadLabel="#{langueBean.getMsg('upOpt2')}" allowTypes="/(\.|\/)(skos|rdf|xml)$/"
                              cancelLabel="#{langueBean.getMsg('upOpt3')}" fileUploadListener="#{rdf4jFileBean.chargeFile}" process="@form"
                              onstart="PrimeFaces.monitorDownload(start_import_concept);PF('pbAjax').start();" 
                              update="@form" oncomplete="PrimeFaces.monitorDownload(stop_import_concept)" disabled="#{!rdf4jFileBean.uploadEnable}"/>
                
                
                
                <br/> 
                <p:commandButton value="#{langueBean.getMsg('btnAdd')}" disabled="#{!rdf4jFileBean.BDDinsertEnable}" 
                                 actionListener="#{rdf4jFileBean.inserSingleConcept(editionBean.selectedUserGroup,selectedTerme)}" 
                                 onclick="PrimeFaces.monitorDownload(start_import_concept);PF('pbAjax').start();" 
                                 oncomplete="PrimeFaces.monitorDownload(stop_import_concept);PF('importSingleConceptDlg').hide();" 
                                 update="idImportSingleConceptDlg,:accordeonTree,:panContenu"
                                 />
            </h:form>



            <p:dialog modal="true" widgetVar="importWait" header="#{langueBean.getMsg('export.wait')}" draggable="false" closable="false" resizable="false">
                <p:graphicImage id="exportLoadingImage" value="/images/loading.gif" width="50"/>

                <br />
                <p:progressBar widgetVar="pbAjax" ajax="true" value="0" labelTemplate="{value}%" styleClass="animated" global="false"/>


            </p:dialog>


        </p:dialog>

        <script type="text/javascript">
            function start_import_concept() {
                PF('importWait').show();
            }

            function stop_import_concept() {
                PF('importWait').hide();

            }
        </script> 


    </ui:composition>